### ISSUE TITLE
Generation - Loading pre-trained weights

### ISSUE THREAD

**Issue by sjcv** [KunalMGupta/NeuralMeshFlow#2]
Hi, thanks for the cool work. 

For the generation task for SVR, why are you loading the weights of the AE model?
https://github.com/KunalMGupta/NeuralMeshFlow/blob/3749ae1ed71665fc2a283df1f8bf3fad9496d638/generate.py#L39

**Comment by KunalMGupta** [comment]
At its core NMF is an auto-encoder. For SVR, we first predict a sparse point cloud and then feed this to the NMF. Check out: https://github.com/KunalMGupta/NeuralMeshFlow/blob/3749ae1ed71665fc2a283df1f8bf3fad9496d638/model/model.py#L378

**Comment by sjcv** [comment]
Thanks! Closing.
