### ISSUE TITLE
Pose for training SVR

### ISSUE THREAD

**Issue by sjcv** [KunalMGupta/NeuralMeshFlow#3]
Hi, you didn't make use of the pose information(camera angles) of the images for training in the SVR task. Aren't they required  for transforming the gt mesh/points or am I missing something?

**Comment by KunalMGupta** [comment]
NMF predicts the meshes in a canonical orientation (same as ground truth). Therefore, we do not need to apply any transformation.

**Comment by sjcv** [comment]
Thanks for clarifying.
