### ISSUE TITLE
Same mesh of a  'sofa'  is being generated for images not in the given samples provided in colab  

### ISSUE THREAD

**Issue by husnain-ali21** [KunalMGupta/NeuralMeshFlow#6]
I tried to generate a mesh for a box and other objects but the model only outputs correct meshes for given sample images .

**Comment by KunalMGupta** [comment]
Hi, can you elaborate a bit more on the kind of images you tried it with? Since the model is trained on ShapeNet categories, it will work best for those. But it should still generalize to similar images from non-shapenet datasets.

**Comment by husnain-ali21** [comment]
Hi that actually explains a lot I tried an image of a screw and a box.
